<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fdl</string>
	</array>
	<key>name</key>
	<string>fuzzyDL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>"(.*)"</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>sign</string>
			<key>match</key>
			<string>(&gt;=|&lt;=|=)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>number</string>
			<key>match</key>
			<string>[^A-Za-z0-9](-?([0-9])*[.]?[0-9]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>query reserved word</string>
			<key>match</key>
			<string>(max-instance[?]|min-instance[?]|classify[?]|all-instances[?]|max-related[?]|min-related[?]|max-subs[?]|max-g-subs[?]|max-l-subs[?]|max-kd-subs[?]|min-subs[?]|min-g-subs[?]|min-l-subs[?]|min-kd-subs[?]|max-sat[?]|min-sat[?]|max-var[?]|min-var[?]|sat[?]|defuzzify-lom[?]|defuzzify-som[?]|defuzzify-mom[?]|bnp[?])</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>axiom reserved word</string>
			<key>match</key>
			<string>([(])(related|instance|define-truth-constant|define-concept|define-primitive-concept|equivalent-concepts|define-fuzzy-concept|define-fuzzy-number|define-fuzzy-number-range|define-fuzzy-similarity|define-fuzzy-equivalence|related|define-modifier|functional|transitive|reflexive|symmetric|implies-role|inverse|inverse-functional|disjoint|disjoint-union|range|domain|constraints|free|binary|define-fuzzy-logic|crisp-concept|crisp-role|show-variables|show-abstract-fillers|show-abstract-fillers-for|show-concrete-fillers|show-concrete-fillers-for|show-concrete-instance-for|show-instances|show-concepts|show-language)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>top and bottom concept reserved word</string>
			<key>match</key>
			<string>[*](top|bottom)[*]</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>concept reserved word</string>
			<key>match</key>
			<string>([(])(and|g-and|l-and|implies|g-implies|kd-implies|l-implies|z-implies|or|g-or|l-or|not|some|b-some|all|w-sum|w-sum-zero|w-max|w-min|self|ua|la|owa|q-owa|choquet|sugeno|q-sugeno|tua|tla|lua|lla|f[+]|f-|f[*]|f/)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>constant reserved word</string>
			<key>match</key>
			<string>(crisp|left-shoulder|right-shoulder|triangular|trapezoidal|linear|modified|linear-modifier|triangular-modifier|lukasiewicz|zadeh|classical|[*]string[*]|[*]boolean[*]|[*]real[*]|[*]integer[*])</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>in-line comment with #</string>
			<key>match</key>
			<string>^(#.*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>in-line comment with %</string>
			<key>match</key>
			<string>^(%.*)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fuzzyDL</string>
	<key>uuid</key>
	<string>b8ea182d-301e-49f1-aa2b-93b2f1f0106b</string>
</dict>
</plist>
