/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package fuzzydl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int INSTANCE = 5;
  /** RegularExpression Id. */
  int MAX_INSTANCE_QUERY = 6;
  /** RegularExpression Id. */
  int MIN_INSTANCE_QUERY = 7;
  /** RegularExpression Id. */
  int ALL_INSTANCE_QUERY = 8;
  /** RegularExpression Id. */
  int MAX_RELATED_QUERY = 9;
  /** RegularExpression Id. */
  int MIN_RELATED_QUERY = 10;
  /** RegularExpression Id. */
  int MAX_SUBSUMES_QUERY = 11;
  /** RegularExpression Id. */
  int MAX_G_SUBSUMES_QUERY = 12;
  /** RegularExpression Id. */
  int MAX_L_SUBSUMES_QUERY = 13;
  /** RegularExpression Id. */
  int MAX_KD_SUBSUMES_QUERY = 14;
  /** RegularExpression Id. */
  int MIN_SUBSUMES_QUERY = 15;
  /** RegularExpression Id. */
  int MIN_G_SUBSUMES_QUERY = 16;
  /** RegularExpression Id. */
  int MIN_L_SUBSUMES_QUERY = 17;
  /** RegularExpression Id. */
  int MIN_KD_SUBSUMES_QUERY = 18;
  /** RegularExpression Id. */
  int MAX_SATISFIABLE_QUERY = 19;
  /** RegularExpression Id. */
  int MIN_SATISFIABLE_QUERY = 20;
  /** RegularExpression Id. */
  int CLASSIFY = 21;
  /** RegularExpression Id. */
  int MAX_QUERY = 22;
  /** RegularExpression Id. */
  int MIN_QUERY = 23;
  /** RegularExpression Id. */
  int SATISFIABLE_QUERY = 24;
  /** RegularExpression Id. */
  int LOM_DEFUZZIFY_QUERY = 25;
  /** RegularExpression Id. */
  int SOM_DEFUZZIFY_QUERY = 26;
  /** RegularExpression Id. */
  int MOM_DEFUZZIFY_QUERY = 27;
  /** RegularExpression Id. */
  int BNP_QUERY = 28;
  /** RegularExpression Id. */
  int DEFINE_TRUTH_CONSTANT = 29;
  /** RegularExpression Id. */
  int DEFINE_CONCEPT = 30;
  /** RegularExpression Id. */
  int DEFINE_PRIMITIVE_CONCEPT = 31;
  /** RegularExpression Id. */
  int EQUIVALENT_CONCEPTS = 32;
  /** RegularExpression Id. */
  int DEFINE_FUZZY_CONCEPT = 33;
  /** RegularExpression Id. */
  int DEFINE_FUZZY_NUMBER = 34;
  /** RegularExpression Id. */
  int DEFINE_FUZZY_NUMBER_RANGE = 35;
  /** RegularExpression Id. */
  int DEFINE_FUZZY_SIMILARITY = 36;
  /** RegularExpression Id. */
  int DEFINE_FUZZY_EQUIVALENCE = 37;
  /** RegularExpression Id. */
  int RELATED = 38;
  /** RegularExpression Id. */
  int DEFINE_MODIFIER = 39;
  /** RegularExpression Id. */
  int FUNCTIONAL = 40;
  /** RegularExpression Id. */
  int TRANSITIVE = 41;
  /** RegularExpression Id. */
  int REFLEXIVE = 42;
  /** RegularExpression Id. */
  int SYMMETRIC = 43;
  /** RegularExpression Id. */
  int IMPLIES_ROLE = 44;
  /** RegularExpression Id. */
  int INVERSE = 45;
  /** RegularExpression Id. */
  int INVERSE_FUNCTIONAL = 46;
  /** RegularExpression Id. */
  int DISJOINT = 47;
  /** RegularExpression Id. */
  int DISJOINT_UNION = 48;
  /** RegularExpression Id. */
  int RANGE = 49;
  /** RegularExpression Id. */
  int DOMAIN = 50;
  /** RegularExpression Id. */
  int CONSTRAINTS = 51;
  /** RegularExpression Id. */
  int FUZZY_LOGIC = 52;
  /** RegularExpression Id. */
  int CRISP_CONCEPT = 53;
  /** RegularExpression Id. */
  int CRISP_ROLE = 54;
  /** RegularExpression Id. */
  int COM = 55;
  /** RegularExpression Id. */
  int AND = 56;
  /** RegularExpression Id. */
  int G_AND = 57;
  /** RegularExpression Id. */
  int L_AND = 58;
  /** RegularExpression Id. */
  int IMPLIES = 59;
  /** RegularExpression Id. */
  int G_IMPLIES = 60;
  /** RegularExpression Id. */
  int KD_IMPLIES = 61;
  /** RegularExpression Id. */
  int L_IMPLIES = 62;
  /** RegularExpression Id. */
  int Z_IMPLIES = 63;
  /** RegularExpression Id. */
  int OR = 64;
  /** RegularExpression Id. */
  int G_OR = 65;
  /** RegularExpression Id. */
  int L_OR = 66;
  /** RegularExpression Id. */
  int NOT = 67;
  /** RegularExpression Id. */
  int SOME = 68;
  /** RegularExpression Id. */
  int HAS_VALUE = 69;
  /** RegularExpression Id. */
  int ALL = 70;
  /** RegularExpression Id. */
  int TOP = 71;
  /** RegularExpression Id. */
  int BOTTOM = 72;
  /** RegularExpression Id. */
  int W_SUM = 73;
  /** RegularExpression Id. */
  int W_SUM_ZERO = 74;
  /** RegularExpression Id. */
  int W_MAX = 75;
  /** RegularExpression Id. */
  int W_MIN = 76;
  /** RegularExpression Id. */
  int SELF = 77;
  /** RegularExpression Id. */
  int UPPER_APPROX = 78;
  /** RegularExpression Id. */
  int LOWER_APPROX = 79;
  /** RegularExpression Id. */
  int OWA = 80;
  /** RegularExpression Id. */
  int QOWA = 81;
  /** RegularExpression Id. */
  int CHOQUET = 82;
  /** RegularExpression Id. */
  int SUGENO = 83;
  /** RegularExpression Id. */
  int QSUGENO = 84;
  /** RegularExpression Id. */
  int TIGHT_UPPER_APPROX = 85;
  /** RegularExpression Id. */
  int TIGHT_LOWER_APPROX = 86;
  /** RegularExpression Id. */
  int LOOSE_UPPER_APPROX = 87;
  /** RegularExpression Id. */
  int LOOSE_LOWER_APPROX = 88;
  /** RegularExpression Id. */
  int FUZZY_NUMBER_ADD = 89;
  /** RegularExpression Id. */
  int FUZZY_NUMBER_MINUS = 90;
  /** RegularExpression Id. */
  int FUZZY_NUMBER_MULT = 91;
  /** RegularExpression Id. */
  int FUZZY_NUMBER_DIV = 92;
  /** RegularExpression Id. */
  int SIGMA_COUNT = 93;
  /** RegularExpression Id. */
  int CRISP = 94;
  /** RegularExpression Id. */
  int LS = 95;
  /** RegularExpression Id. */
  int RS = 96;
  /** RegularExpression Id. */
  int TRI = 97;
  /** RegularExpression Id. */
  int TRAP = 98;
  /** RegularExpression Id. */
  int LINEAR = 99;
  /** RegularExpression Id. */
  int MODIFIED = 100;
  /** RegularExpression Id. */
  int LM = 101;
  /** RegularExpression Id. */
  int TRIAM = 102;
  /** RegularExpression Id. */
  int SHOW_VARIABLES = 103;
  /** RegularExpression Id. */
  int SHOW_ABSTRACT_FILLER = 104;
  /** RegularExpression Id. */
  int SHOW_ABSTRACT_FILLER_FOR = 105;
  /** RegularExpression Id. */
  int SHOW_CONCRETE_FILLER = 106;
  /** RegularExpression Id. */
  int SHOW_CONCRETE_FILLER_FOR = 107;
  /** RegularExpression Id. */
  int SHOW_CONCRETE_FILLER_AND_LABELS = 108;
  /** RegularExpression Id. */
  int SHOW_INSTANCES = 109;
  /** RegularExpression Id. */
  int SHOW_CONCEPTS = 110;
  /** RegularExpression Id. */
  int SHOW_LANGUAGE = 111;
  /** RegularExpression Id. */
  int FR = 112;
  /** RegularExpression Id. */
  int BV = 113;
  /** RegularExpression Id. */
  int LUKASIEWICZ = 114;
  /** RegularExpression Id. */
  int ZADEH = 115;
  /** RegularExpression Id. */
  int CLASSICAL = 116;
  /** RegularExpression Id. */
  int PLUS = 117;
  /** RegularExpression Id. */
  int MINUS = 118;
  /** RegularExpression Id. */
  int STAR = 119;
  /** RegularExpression Id. */
  int LESS = 120;
  /** RegularExpression Id. */
  int GRE = 121;
  /** RegularExpression Id. */
  int EQL = 122;
  /** RegularExpression Id. */
  int NUMBER = 123;
  /** RegularExpression Id. */
  int IDENTIFIER = 124;
  /** RegularExpression Id. */
  int OP = 125;
  /** RegularExpression Id. */
  int CP = 126;
  /** RegularExpression Id. */
  int OSB = 127;
  /** RegularExpression Id. */
  int CSB = 128;
  /** RegularExpression Id. */
  int OCB = 129;
  /** RegularExpression Id. */
  int CCB = 130;
  /** RegularExpression Id. */
  int COMMENT_MARK = 131;
  /** RegularExpression Id. */
  int COMMA = 132;
  /** RegularExpression Id. */
  int STRING_TYPE = 133;
  /** RegularExpression Id. */
  int BOOLEAN_TYPE = 134;
  /** RegularExpression Id. */
  int NUMBER_TYPE = 135;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<SINGLE_LINE_COMMENT>",
    "<EOL>",
    "\"instance\"",
    "\"max-instance?\"",
    "\"min-instance?\"",
    "\"all-instances?\"",
    "\"max-related?\"",
    "\"min-related?\"",
    "\"max-subs?\"",
    "\"max-g-subs?\"",
    "\"max-l-subs?\"",
    "\"max-kd-subs?\"",
    "\"min-subs?\"",
    "\"min-g-subs?\"",
    "\"min-l-subs?\"",
    "\"min-kd-subs?\"",
    "\"max-sat?\"",
    "\"min-sat?\"",
    "\"classify?\"",
    "\"max-var?\"",
    "\"min-var?\"",
    "\"sat?\"",
    "\"defuzzify-lom?\"",
    "\"defuzzify-som?\"",
    "\"defuzzify-mom?\"",
    "\"bnp?\"",
    "\"define-truth-constant\"",
    "\"define-concept\"",
    "\"define-primitive-concept\"",
    "\"equivalent-concepts\"",
    "\"define-fuzzy-concept\"",
    "\"define-fuzzy-number\"",
    "\"define-fuzzy-number-range\"",
    "\"define-fuzzy-similarity\"",
    "\"define-fuzzy-equivalence\"",
    "\"related\"",
    "\"define-modifier\"",
    "\"functional\"",
    "\"transitive\"",
    "\"reflexive\"",
    "\"symmetric\"",
    "\"implies-role\"",
    "\"inverse\"",
    "\"inverse-functional\"",
    "\"disjoint\"",
    "\"disjoint-union\"",
    "\"range\"",
    "\"domain\"",
    "\"constraints\"",
    "\"define-fuzzy-logic\"",
    "\"crisp-concept\"",
    "\"crisp-role\"",
    "\"\\\"\"",
    "\"and\"",
    "\"g-and\"",
    "\"l-and\"",
    "\"implies\"",
    "\"g-implies\"",
    "\"kd-implies\"",
    "\"l-implies\"",
    "\"z-implies\"",
    "\"or\"",
    "\"g-or\"",
    "\"l-or\"",
    "\"not\"",
    "\"some\"",
    "\"b-some\"",
    "\"all\"",
    "\"*top*\"",
    "\"*bottom*\"",
    "\"w-sum\"",
    "\"w-sum-zero\"",
    "\"w-max\"",
    "\"w-min\"",
    "\"self\"",
    "\"ua\"",
    "\"la\"",
    "\"owa\"",
    "\"q-owa\"",
    "\"choquet\"",
    "\"sugeno\"",
    "\"q-sugeno\"",
    "\"tua\"",
    "\"tla\"",
    "\"lua\"",
    "\"lla\"",
    "\"f+\"",
    "\"f-\"",
    "\"f*\"",
    "\"f/\"",
    "\"sigma-count\"",
    "\"crisp\"",
    "\"left-shoulder\"",
    "\"right-shoulder\"",
    "\"triangular\"",
    "\"trapezoidal\"",
    "\"linear\"",
    "\"modified\"",
    "\"linear-modifier\"",
    "\"triangular-modifier\"",
    "\"show-variables\"",
    "\"show-abstract-fillers\"",
    "\"show-abstract-fillers-for\"",
    "\"show-concrete-fillers\"",
    "\"show-concrete-fillers-for\"",
    "\"show-concrete-instance-for\"",
    "\"show-instances\"",
    "\"show-concepts\"",
    "\"show-language\"",
    "\"free\"",
    "\"binary\"",
    "\"lukasiewicz\"",
    "\"zadeh\"",
    "\"classical\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"#\"",
    "\",\"",
    "\"*string*\"",
    "\"*boolean*\"",
    "<NUMBER_TYPE>",
  };

}
