/* ParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
package fuzzydl.parser;
import java.io.*;
import java.util.*;
import fuzzydl.*;
import fuzzydl.exception.*;
import fuzzydl.milp.*;
import fuzzydl.util.*;

/** Token Manager. */
@SuppressWarnings ("unused")
public class ParserTokenManager implements ParserConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2){
   switch (pos)
   {
      case 0:
         if ((active1 & 0x80000000000180L) != 0L || (active2 & 0x60L) != 0L)
            return 23;
         if ((active0 & 0xff7fffffffffffe0L) != 0L || (active1 & 0x1ffffffffffe7fL) != 0L)
         {
            jjmatchedKind = 124;
            return 31;
         }
         if ((active1 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 124;
            return 17;
         }
         if ((active2 & 0x8L) != 0L)
            return 32;
         if ((active1 & 0x40000000000000L) != 0L)
            return 33;
         return -1;
      case 1:
         if ((active0 & 0xff7fffffffffffe0L) != 0L || (active1 & 0x1fffffe1ff3e7eL) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 1;
            return 31;
         }
         if ((active1 & 0x1400c001L) != 0L)
            return 31;
         if ((active1 & 0x2000000L) != 0L)
            return 17;
         return -1;
      case 2:
         if ((active0 & 0xfe7ffffffffffee0L) != 0L || (active1 & 0x1fffffe01e3e36L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 124;
               jjmatchedPos = 2;
            }
            return 31;
         }
         if ((active0 & 0x100000000000100L) != 0L || (active1 & 0x1e10048L) != 0L)
            return 31;
         return -1;
      case 3:
         if ((active1 & 0x1000000002016L) != 0L)
            return 31;
         if ((active0 & 0xfe7fffffeeffffe0L) != 0L || (active1 & 0x1effffe01e1e20L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 3;
            return 31;
         }
         return -1;
      case 4:
         if ((active0 & 0xf81dffffeeffffe0L) != 0L || (active1 & 0x16ffffa01c0020L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 124;
               jjmatchedPos = 4;
            }
            return 31;
         }
         if ((active0 & 0x662000000000000L) != 0L || (active1 & 0x8000040021e00L) != 0L)
            return 31;
         return -1;
      case 5:
         if ((active0 & 0x4000000000000L) != 0L || (active1 & 0x2002800080020L) != 0L)
            return 31;
         if ((active0 & 0xf879ffffeeffffe0L) != 0L || (active1 & 0x14ffd7a0140400L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 124;
               jjmatchedPos = 5;
            }
            return 31;
         }
         return -1;
      case 6:
         if ((active0 & 0xf0798fbfeeffffe0L) != 0L || (active1 & 0x14fff7a0100400L) != 0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 124;
               jjmatchedPos = 6;
            }
            return 31;
         }
         if ((active0 & 0x800704000000000L) != 0L || (active1 & 0x40000L) != 0L)
            return 31;
         return -1;
      case 7:
         if ((active0 & 0xf0785fbfee27ffc0L) != 0L || (active1 & 0x14ffe7a0000400L) != 0L)
         {
            if (jjmatchedPos != 7)
            {
               jjmatchedKind = 124;
               jjmatchedPos = 7;
            }
            return 31;
         }
         if ((active0 & 0x1800000000020L) != 0L || (active1 & 0x1000100000L) != 0L)
            return 31;
         return -1;
      case 8:
         if ((active0 & 0xd0000c0000000000L) != 0L || (active1 & 0x10000000000000L) != 0L)
            return 31;
         if ((active0 & 0x207953bfee0777c0L) != 0L || (active1 & 0x4ffe7a0000400L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 8;
            return 31;
         }
         return -1;
      case 9:
         if ((active0 & 0x2040030000000000L) != 0L || (active1 & 0x4200000400L) != 0L)
            return 31;
         if ((active0 & 0x3950bfee0777c0L) != 0L || (active1 & 0x4ffa5a0000000L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 124;
               jjmatchedPos = 9;
            }
            return 31;
         }
         return -1;
      case 10:
         if ((active0 & 0x3150bfee0447c0L) != 0L || (active1 & 0xffe180000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 10;
            return 31;
         }
         if ((active0 & 0x8000000000000L) != 0L || (active1 & 0x4000420000000L) != 0L)
            return 31;
         return -1;
      case 11:
         if ((active0 & 0x3140bfee0001c0L) != 0L || (active1 & 0xffe180000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 11;
            return 31;
         }
         if ((active0 & 0x100000000000L) != 0L)
            return 31;
         return -1;
      case 12:
         if ((active0 & 0x1140bfee000100L) != 0L || (active1 & 0x3fe100000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 12;
            return 31;
         }
         if ((active0 & 0x20000000000000L) != 0L || (active1 & 0xc00080000000L) != 0L)
            return 31;
         return -1;
      case 13:
         if ((active0 & 0x1040bfa0000000L) != 0L || (active1 & 0x1f6000000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 13;
            return 31;
         }
         if ((active0 & 0x1000040000000L) != 0L || (active1 & 0x208100000000L) != 0L)
            return 31;
         return -1;
      case 14:
         if ((active0 & 0x10403fa0000000L) != 0L || (active1 & 0x1f4000000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 14;
            return 31;
         }
         if ((active0 & 0x8000000000L) != 0L || (active1 & 0x2000000000L) != 0L)
            return 31;
         return -1;
      case 15:
         if ((active0 & 0x10403fa0000000L) != 0L || (active1 & 0x1f4000000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 15;
            return 31;
         }
         return -1;
      case 16:
         if ((active0 & 0x10403fa0000000L) != 0L || (active1 & 0x1f4000000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 16;
            return 31;
         }
         return -1;
      case 17:
         if ((active0 & 0x10400000000000L) != 0L)
            return 31;
         if ((active0 & 0x3fa0000000L) != 0L || (active1 & 0x1f4000000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 17;
            return 31;
         }
         return -1;
      case 18:
         if ((active0 & 0x32a0000000L) != 0L || (active1 & 0x1f0000000000L) != 0L)
         {
            if (jjmatchedPos != 18)
            {
               jjmatchedKind = 124;
               jjmatchedPos = 18;
            }
            return 31;
         }
         if ((active0 & 0xd00000000L) != 0L || (active1 & 0x4000000000L) != 0L)
            return 31;
         return -1;
      case 19:
         if ((active0 & 0x200000000L) != 0L)
            return 31;
         if ((active0 & 0x38a0000000L) != 0L || (active1 & 0x1f0000000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 19;
            return 31;
         }
         return -1;
      case 20:
         if ((active0 & 0x20000000L) != 0L || (active1 & 0xf0000000000L) != 0L)
            return 31;
         if ((active0 & 0x3880000000L) != 0L || (active1 & 0x100000000000L) != 0L)
         {
            if (jjmatchedPos != 20)
            {
               jjmatchedKind = 124;
               jjmatchedPos = 20;
            }
            return 31;
         }
         return -1;
      case 21:
         if ((active0 & 0x3880000000L) != 0L || (active1 & 0x1a0000000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 21;
            return 31;
         }
         return -1;
      case 22:
         if ((active0 & 0x2880000000L) != 0L || (active1 & 0x1a0000000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 22;
            return 31;
         }
         if ((active0 & 0x1000000000L) != 0L)
            return 31;
         return -1;
      case 23:
         if ((active0 & 0x800000000L) != 0L || (active1 & 0x1a0000000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 23;
            return 31;
         }
         if ((active0 & 0x2080000000L) != 0L)
            return 31;
         return -1;
      case 24:
         if ((active1 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 24;
            return 31;
         }
         if ((active0 & 0x800000000L) != 0L || (active1 & 0xa0000000000L) != 0L)
            return 31;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1, long active2){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 34:
         return jjStopAtPos(0, 55);
      case 35:
         return jjStartNfaWithStates_0(0, 131, 32);
      case 40:
         return jjStopAtPos(0, 125);
      case 41:
         return jjStopAtPos(0, 126);
      case 42:
         jjmatchedKind = 119;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x180L, 0x60L);
      case 43:
         return jjStopAtPos(0, 117);
      case 44:
         return jjStopAtPos(0, 132);
      case 45:
         return jjStartNfaWithStates_0(0, 118, 33);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000000000L, 0x0L);
      case 61:
         return jjStopAtPos(0, 122);
      case 62:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000000000000L, 0x0L);
      case 91:
         return jjStopAtPos(0, 127);
      case 93:
         return jjStopAtPos(0, 128);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x100000000000100L, 0x40L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x10000000L, 0x2000000000020L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x68000000200000L, 0x10000040040000L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1580beee000000L, 0x0L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x100000000L, 0x0L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x10000000000L, 0x100001e000000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x1200000000000000L, 0x2L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x800700000000020L, 0x0L, 0x0L);
      case 107:
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L, 0x0L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x4400000000000000L, 0x4002881808004L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0xdffec0L, 0x1000000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10001L, 0x0L);
      case 113:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x120000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x2044000000000L, 0x100000000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x80001000000L, 0xff8020082010L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x20000000000L, 0x4600600000L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1e00L, 0x0L);
      case 122:
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L, 0x8000000000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 129);
      case 125:
         return jjStopAtPos(0, 130);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 42:
         if ((active1 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 91);
         break;
      case 43:
         if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(1, 89, 17);
         break;
      case 45:
         if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(1, 90, 31);
         return jjMoveStringLiteralDfa2_0(active0, 0xd600000000000000L, active1, 0x121e26L, active2, 0L);
      case 47:
         if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(1, 92, 31);
         break;
      case 61:
         if ((active1 & 0x100000000000000L) != 0L)
            return jjStopAtPos(1, 120);
         else if ((active1 & 0x200000000000000L) != 0L)
            return jjStopAtPos(1, 121);
         break;
      case 97:
         if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(1, 78, 31);
         else if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(1, 79, 31);
         return jjMoveStringLiteralDfa2_0(active0, 0x2000001487a40L, active1, 0x8000000000000L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100L, active2, 0x40L);
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000000000L, active1, 0L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x1004feee000000L, active1, 0x80002000L, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0xff8000040000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800000978480L, active1, 0x2002920000000L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x200100L, active1, 0x10000001400040L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x800100000000000L, active1, 0L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x100600010000020L, active1, 0L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0xc000000000000L, active1, 0x1000000018L, active2, 0L);
      case 113:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L, active1, 0L, active2, 0L);
      case 114:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(1, 64, 31);
         return jjMoveStringLiteralDfa2_0(active0, 0x60020000000000L, active1, 0x1004640000000L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x20L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000000L, active1, 0x4000000a80000L, active2, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10000L, active2, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000000L, active1, 0L, active2, 0L);
      case 97:
         if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(2, 80, 31);
         else if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(2, 85, 31);
         else if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 86, 31);
         else if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 87, 31);
         else if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(2, 88, 31);
         return jjMoveStringLiteralDfa3_0(active0, 0x600020000200000L, active1, 0x10000400000000L, active2, 0L);
      case 100:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 56, 31);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x8001000000000L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1000000000000L, active2, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x1004beee000000L, active1, 0x80000000L, active2, 0L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x120080000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0xd060000000000000L, active1, 0x4240000000L, active2, 0L);
      case 107:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4000000000000L, active2, 0L);
      case 108:
         if ((active1 & 0x40L) != 0L)
         {
            jjmatchedKind = 70;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000100L, active1, 0x2000L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x4080000000000L, active1, 0x1810L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0xa010000978480L, active1, 0x2002800000000L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0xff8000060186L, active2, 0x40L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x800100010000000L, active1, 0L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x1800000000020L, active1, 0x100620L, active2, 0L);
      case 116:
         if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(2, 67, 31);
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000L, active1, 0L, active2, 0x20L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L, active1, 0L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x600000000000L, active1, 0L, active2, 0L);
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x487a40L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, active2);
      return 3;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa4_0(active0, 0xdfffc0L, active1, 0L, active2, 0L);
      case 63:
         if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(3, 24);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(3, 28);
         break;
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x4004000000000L, active1, 0x6004200000800L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L, active1, 0L, active2, 0L);
      case 101:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(3, 68, 31);
         else if ((active1 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 112, 31);
         return jjMoveStringLiteralDfa4_0(active0, 0x600000000000L, active1, 0x8002800080000L, active2, 0L);
      case 102:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 77, 31);
         break;
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000L, active1, 0L, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x100000000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x201000bfe0000000L, active1, 0x1000001000L, active2, 0L);
      case 106:
         return jjMoveStringLiteralDfa4_0(active0, 0x1800000000000L, active1, 0L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x800140000000000L, active1, 0L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0xd000080000000000L, active1, 0x20000000L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x600020000000000L, active1, 0L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x20L, active2, 0x40L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400000080L, active2, 0L);
      case 113:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x40000L, active2, 0L);
      case 114:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(3, 65, 31);
         else if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(3, 66, 31);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0L, active2, 0x20L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x68000000200000L, active1, 0x10000040000000L, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x20L, active1, 0x80000100L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0xe000000L, active1, 0x100600L, active2, 0L);
      case 119:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0xff8000020000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, active2);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(2, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, active2);
      return 4;
   }
   switch(curChar)
   {
      case 42:
         if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(4, 71);
         break;
      case 45:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0xff8080000000L, active2, 0L);
      case 97:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(4, 81, 31);
         return jjMoveStringLiteralDfa5_0(active0, 0x20L, active1, 0x2820000000L, active2, 0L);
      case 100:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 57, 31);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 58, 31);
         break;
      case 101:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 49, 31);
         return jjMoveStringLiteralDfa5_0(active0, 0xc0000000000L, active1, 0x400000000L, active2, 0L);
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x1000000000L, active2, 0L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x11000L, active1, 0x100000L, active2, 0L);
      case 104:
         if ((active1 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 115, 31);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x8041000000001c0L, active1, 0L, active2, 0x20L);
      case 107:
         return jjMoveStringLiteralDfa5_0(active0, 0x44000L, active1, 0L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x22000L, active1, 0L, active2, 0x40L);
      case 109:
         if ((active1 & 0x200L) != 0L)
         {
            jjmatchedKind = 73;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000000L, active1, 0x420L, active2, 0L);
      case 110:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 76, 31);
         return jjMoveStringLiteralDfa5_0(active0, 0x1000bee0000000L, active1, 0x4200080000L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x1800000000000L, active1, 0L, active2, 0L);
      case 112:
         if ((active1 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0xd060000000000000L, active1, 0L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x600000000600L, active1, 0x2000000000000L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000388800L, active1, 0x14000000000000L, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x8014000000000L, active1, 0x100000100L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x40000L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa5_0(active0, 0x100c00000L, active1, 0L, active2, 0L);
      case 120:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 75, 31);
         break;
      case 122:
         return jjMoveStringLiteralDfa5_0(active0, 0xe000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, active2);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(3, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, active2);
      return 5;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa6_0(active0, 0x60000000033000L, active1, 0x120000400L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x100d80000L, active1, 0x30000000000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x5c0000000000L, active2, 0L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x44000L, active1, 0L, active2, 0L);
      case 101:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(5, 69, 31);
         return jjMoveStringLiteralDfa6_0(active0, 0x81010fee0000600L, active1, 0x140000L, active2, 0x40L);
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x4200000000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x1830000200000L, active1, 0x14201000000000L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0xd000000000000000L, active1, 0x800000000000L, active2, 0L);
      case 110:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 50, 31);
         return jjMoveStringLiteralDfa6_0(active0, 0x1e0L, active1, 0L, active2, 0x20L);
      case 111:
         if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(5, 83, 31);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x100L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000000000L, active1, 0L, active2, 0L);
      case 114:
         if ((active1 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000L, active1, 0x2000000000L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x600000000000L, active1, 0x80000000L, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000L, active1, 0L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x8800L, active1, 0L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x8000000000L, active2, 0L);
      case 120:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L, active1, 0L, active2, 0L);
      case 121:
         if ((active1 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 113, 31);
         break;
      case 122:
         return jjMoveStringLiteralDfa6_0(active0, 0xe000000L, active1, 0x400000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, active2);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(4, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, active2);
      return 6;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000bee0044000L, active1, 0x2000000000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000L, active1, 0x808000000000L, active2, 0x40L);
      case 98:
         return jjMoveStringLiteralDfa7_0(active0, 0x8800L, active1, 0x30000000000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000020L, active1, 0x10000020000000L, active2, 0L);
      case 100:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 38, 31);
         break;
      case 101:
         if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000L, active1, 0x4001000000000L, active2, 0L);
      case 102:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000L, active1, 0L, active2, 0L);
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x20L);
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x80000000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0xd00004000e000000L, active1, 0L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000100000600L, active1, 0L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x100L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x1800000000000L, active1, 0x200000100000L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000L, active1, 0x5c0400000000L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x40080000c00000L, active1, 0L, active2, 0L);
      case 115:
         if ((active0 & 0x800000000000000L) != 0L)
         {
            jjmatchedKind = 59;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000331c0L, active1, 0x100000000L, active2, 0L);
      case 116:
         if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(6, 82, 31);
         return jjMoveStringLiteralDfa7_0(active0, 0x20000180000L, active1, 0L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x4200000000L, active2, 0L);
      case 122:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x400L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, active2);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(5, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, active2);
      return 7;
   }
   switch(curChar)
   {
      case 42:
         if ((active1 & 0x100L) != 0L)
            return jjStopAtPos(7, 72);
         else if ((active2 & 0x20L) != 0L)
            return jjStopAtPos(7, 133);
         break;
      case 45:
         return jjMoveStringLiteralDfa8_0(active0, 0x500000000000L, active1, 0L, active2, 0L);
      case 63:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(7, 19);
         else if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(7, 20);
         else if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(7, 22);
         else if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(7, 23);
         break;
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x600L, active1, 0x10000000000000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000L, active1, 0L, active2, 0L);
      case 100:
         if ((active1 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 100, 31);
         break;
      case 101:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(7, 5, 31);
         return jjMoveStringLiteralDfa8_0(active0, 0xd000000100000000L, active1, 0x400L, active2, 0L);
      case 102:
         return jjMoveStringLiteralDfa8_0(active0, 0x10003e0e000000L, active1, 0L, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x100000000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x20080a0000000000L, active1, 0x400000000L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x4200000000L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000L, active1, 0x2000000000L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000L, active1, 0xdc0000000000L, active2, 0x40L);
      case 111:
         if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(7, 84, 31);
         return jjMoveStringLiteralDfa8_0(active0, 0x60000000000000L, active1, 0xa0000000L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000L, active1, 0L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x8000000000L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa8_0(active0, 0x4c800L, active1, 0x230000000000L, active2, 0L);
      case 116:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x10000200001c0L, active1, 0L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x33000L, active1, 0L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000000L, active1, 0L, active2, 0L);
      case 119:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x4000000000000L, active2, 0L);
      case 121:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, active2);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(6, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1, active2);
      return 8;
   }
   switch(curChar)
   {
      case 42:
         if ((active2 & 0x40L) != 0L)
            return jjStopAtPos(8, 134);
         break;
      case 45:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000000L, active1, 0L, active2, 0L);
      case 63:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(8, 11);
         else if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(8, 15);
         else if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(8, 21);
         break;
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000001c0L, active1, 0x4200000000L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa9_0(active0, 0x33000L, active1, 0L, active2, 0L);
      case 99:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 43, 31);
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x5c0000000000L, active2, 0L);
      case 100:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x400000000L, active2, 0L);
      case 101:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 42, 31);
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000000000000L, active1, 0L, active2, 0L);
      case 102:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000000L, active1, 0L, active2, 0L);
      case 103:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x800000000000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x4008000000000L, active2, 0L);
      case 108:
         if ((active1 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 116, 31);
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000000000L, active1, 0L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x28000100000000L, active1, 0L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x8040000000L, active1, 0x2100000000L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000a0000000L, active1, 0x400L, active2, 0L);
      case 115:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 60, 31);
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 62, 31);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 63, 31);
         break;
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x600L, active1, 0x230000000000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa9_0(active0, 0x10003e00044000L, active1, 0xa0000000L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000000L, active1, 0L, active2, 0L);
      case 121:
         return jjMoveStringLiteralDfa9_0(active0, 0xe000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1, active2);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(7, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa10_0(active0, 0xe000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x208400000000L);
      case 98:
         return jjMoveStringLiteralDfa10_0(active0, 0x44000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000000000L, active1, 0x4000000000000L);
      case 100:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000L, active1, 0x2000000000L);
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 41, 31);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 54, 31);
         return jjMoveStringLiteralDfa10_0(active0, 0x600L, active1, 0x400000000000L);
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000L, active1, 0L);
      case 108:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 40, 31);
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x80000000L);
      case 110:
         return jjMoveStringLiteralDfa10_0(active0, 0x400001c0L, active1, 0x20000000L);
      case 111:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(9, 74, 31);
         return jjMoveStringLiteralDfa10_0(active0, 0x100000000000L, active1, 0L);
      case 114:
         if ((active1 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 97;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x1f4000000000L);
      case 115:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 61, 31);
         return jjMoveStringLiteralDfa10_0(active0, 0x33000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000100000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa10_0(active0, 0x1400020000000L, active1, 0x800100000000L);
      case 122:
         return jjMoveStringLiteralDfa10_0(active0, 0x10003e00000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000000L, active1, 0x4000000000L);
      case 63:
         if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(10, 12);
         else if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(10, 13);
         else if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(10, 16);
         else if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(10, 17);
         break;
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x830000000000L);
      case 98:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x8000000000L);
      case 99:
         return jjMoveStringLiteralDfa11_0(active0, 0x400001c0L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa11_0(active0, 0x600L, active1, 0x80000000L);
      case 101:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000000000L, active1, 0x1c0000000000L);
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x8000000000L, active1, 0x2000000000L);
      case 108:
         if ((active1 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(10, 98, 31);
         return jjMoveStringLiteralDfa11_0(active0, 0x100002000000L, active1, 0x100000000L);
      case 109:
         return jjMoveStringLiteralDfa11_0(active0, 0x88000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x1400000000000L, active1, 0x200000000000L);
      case 112:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x400000000000L);
      case 115:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 51, 31);
         return jjMoveStringLiteralDfa11_0(active0, 0x4044000L, active1, 0L);
      case 116:
         if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(10, 93, 31);
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000L, active1, 0L);
      case 122:
         if ((active1 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 114, 31);
         return jjMoveStringLiteralDfa11_0(active0, 0x10003e00000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, active1, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 63:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(11, 9);
         else if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(11, 10);
         else if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(11, 14);
         else if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(11, 18);
         break;
      case 99:
         return jjMoveStringLiteralDfa12_0(active0, 0x400100000000L, active1, 0x230000000000L);
      case 100:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x100000000L);
      case 101:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 44, 31);
         return jjMoveStringLiteralDfa12_0(active0, 0x400001c0L, active1, 0x80000000L);
      case 102:
         return jjMoveStringLiteralDfa12_0(active0, 0x8000000000L, active1, 0x2000000000L);
      case 103:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x800000000000L);
      case 104:
         return jjMoveStringLiteralDfa12_0(active0, 0x20000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000080000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x8000000000L);
      case 109:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x4000000000L);
      case 111:
         return jjMoveStringLiteralDfa12_0(active0, 0xe000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa12_0(active0, 0x20000000000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x5c0000000000L);
      case 121:
         return jjMoveStringLiteralDfa12_0(active0, 0x10003e00000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(10, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, active1, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa13_0(active0, 0x10003e20000000L, active1, 0L);
      case 63:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(12, 6);
         else if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(12, 7);
         break;
      case 101:
         if ((active1 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 111, 31);
         return jjMoveStringLiteralDfa13_0(active0, 0L, active1, 0x3c8100000000L);
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x8000000000L, active1, 0x2000000000L);
      case 109:
         return jjMoveStringLiteralDfa13_0(active0, 0xe000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000100000000L, active1, 0x4000000000L);
      case 112:
         return jjMoveStringLiteralDfa13_0(active0, 0x40000000L, active1, 0L);
      case 114:
         if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(12, 95, 31);
         break;
      case 115:
         if ((active1 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 110, 31);
         return jjMoveStringLiteralDfa13_0(active0, 0x100L, active1, 0L);
      case 116:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 53, 31);
         return jjMoveStringLiteralDfa13_0(active0, 0x400080000000L, active1, 0x30000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(11, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, active1, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa14_0(active0, 0L, active1, 0x1f0000000000L);
      case 63:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(13, 8);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(13, 25);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(13, 26);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(13, 27);
         break;
      case 99:
         return jjMoveStringLiteralDfa14_0(active0, 0x220000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa14_0(active0, 0L, active1, 0x4000000000L);
      case 101:
         return jjMoveStringLiteralDfa14_0(active0, 0xa000000000L, active1, 0x2000000000L);
      case 105:
         return jjMoveStringLiteralDfa14_0(active0, 0x400080000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa14_0(active0, 0x10000000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(13, 48, 31);
         return jjMoveStringLiteralDfa14_0(active0, 0xd00000000L, active1, 0L);
      case 114:
         if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(13, 96, 31);
         break;
      case 115:
         if ((active1 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(13, 103, 31);
         else if ((active1 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(13, 109, 31);
         return jjMoveStringLiteralDfa14_0(active0, 0x1000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(13, 30, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(12, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, active1, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa15_0(active0, 0x100000000L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa15_0(active0, 0L, active1, 0xf0000000000L);
      case 105:
         return jjMoveStringLiteralDfa15_0(active0, 0x1000000000L, active1, 0x104000000000L);
      case 111:
         return jjMoveStringLiteralDfa15_0(active0, 0x10400220000000L, active1, 0L);
      case 113:
         return jjMoveStringLiteralDfa15_0(active0, 0x2000000000L, active1, 0L);
      case 114:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(14, 39, 31);
         else if ((active1 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(14, 101, 31);
         break;
      case 117:
         return jjMoveStringLiteralDfa15_0(active0, 0xc00000000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa15_0(active0, 0x80000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(13, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0, active1, 0L);
      return 15;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa16_0(active0, 0x180000000L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa16_0(active0, 0L, active1, 0x4000000000L);
      case 103:
         return jjMoveStringLiteralDfa16_0(active0, 0x10000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa16_0(active0, 0L, active1, 0xf0000000000L);
      case 109:
         return jjMoveStringLiteralDfa16_0(active0, 0x1c00000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa16_0(active0, 0x400220000000L, active1, 0x100000000000L);
      case 117:
         return jjMoveStringLiteralDfa16_0(active0, 0x2000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(14, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0, active1, 0L);
      return 16;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa17_0(active0, 0x80000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa17_0(active0, 0x400000000000L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa17_0(active0, 0xc00000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa17_0(active0, 0x200000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa17_0(active0, 0x10003000000000L, active1, 0x4000000000L);
      case 108:
         return jjMoveStringLiteralDfa17_0(active0, 0L, active1, 0xf0000000000L);
      case 112:
         return jjMoveStringLiteralDfa17_0(active0, 0x100000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa17_0(active0, 0x20000000L, active1, 0x100000000000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa17_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(15, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0, active1, 0L);
      return 17;
   }
   switch(curChar)
   {
      case 99:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(17, 52, 31);
         return jjMoveStringLiteralDfa18_0(active0, 0x80000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa18_0(active0, 0xe00000000L, active1, 0x4000000000L);
      case 108:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(17, 46, 31);
         return jjMoveStringLiteralDfa18_0(active0, 0x1000000000L, active1, 0xf0000000000L);
      case 116:
         return jjMoveStringLiteralDfa18_0(active0, 0x120000000L, active1, 0x100000000000L);
      case 118:
         return jjMoveStringLiteralDfa18_0(active0, 0x2000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa18_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(16, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0, active1, 0L);
      return 18;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa19_0(active0, 0x3020000000L, active1, 0x100000000000L);
      case 101:
         return jjMoveStringLiteralDfa19_0(active0, 0L, active1, 0xf0000000000L);
      case 111:
         return jjMoveStringLiteralDfa19_0(active0, 0x80000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa19_0(active0, 0x200000000L, active1, 0L);
      case 114:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 18;
         }
         else if ((active1 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(18, 102, 31);
         return jjMoveStringLiteralDfa19_0(active0, 0x800000000L, active1, 0L);
      case 115:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(18, 32, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(17, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa19_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(17, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0, active1, 0L);
      return 19;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa20_0(active0, 0x800000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa20_0(active0, 0x2000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa20_0(active0, 0xa0000000L, active1, 0x100000000000L);
      case 114:
         return jjMoveStringLiteralDfa20_0(active0, 0x1000000000L, active1, 0xf0000000000L);
      case 116:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(19, 33, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(18, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa20_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(18, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, active0, active1, 0L);
      return 20;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa21_0(active0, 0x80000000L, active1, 0x100000000000L);
      case 101:
         return jjMoveStringLiteralDfa21_0(active0, 0x2000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa21_0(active0, 0x1000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa21_0(active0, 0x800000000L, active1, 0L);
      case 115:
         if ((active1 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 104;
            jjmatchedPos = 20;
         }
         else if ((active1 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 106;
            jjmatchedPos = 20;
         }
         return jjMoveStringLiteralDfa21_0(active0, 0L, active1, 0xa0000000000L);
      case 116:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(20, 29, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(19, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa21_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(19, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(20, active0, active1, 0L);
      return 21;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa22_0(active0, 0L, active1, 0xa0000000000L);
      case 97:
         return jjMoveStringLiteralDfa22_0(active0, 0x800000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa22_0(active0, 0x80000000L, active1, 0x100000000000L);
      case 110:
         return jjMoveStringLiteralDfa22_0(active0, 0x2000000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa22_0(active0, 0x1000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(20, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa22_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(20, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(21, active0, active1, 0L);
      return 22;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa23_0(active0, 0L, active1, 0x100000000000L);
      case 99:
         return jjMoveStringLiteralDfa23_0(active0, 0x2000000000L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa23_0(active0, 0L, active1, 0xa0000000000L);
      case 110:
         return jjMoveStringLiteralDfa23_0(active0, 0x800000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa23_0(active0, 0x80000000L, active1, 0L);
      case 121:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(22, 36, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(21, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa23_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(21, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(22, active0, active1, 0L);
      return 23;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(23, 37, 31);
         break;
      case 102:
         return jjMoveStringLiteralDfa24_0(active0, 0L, active1, 0x100000000000L);
      case 103:
         return jjMoveStringLiteralDfa24_0(active0, 0x800000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa24_0(active0, 0L, active1, 0xa0000000000L);
      case 116:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(23, 31, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(22, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa24_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(22, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(23, active0, active1, 0L);
      return 24;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(24, 35, 31);
         break;
      case 111:
         return jjMoveStringLiteralDfa25_0(active0, 0L, active1, 0x100000000000L);
      case 114:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(24, 105, 31);
         else if ((active1 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(24, 107, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(23, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa25_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(23, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(24, 0L, active1, 0L);
      return 25;
   }
   switch(curChar)
   {
      case 114:
         if ((active1 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(25, 108, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(24, 0L, active1, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 31;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 33:
                  if ((0x7ffe08800000000L & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  else if ((0x1000001000000000L & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAdd(17); }
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     { jjCheckNAddStates(0, 3); }
                  }
                  else if (curChar == 46)
                     { jjCheckNAdd(10); }
                  break;
               case 32:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjCheckNAddStates(4, 6); }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 3)
                        kind = 3;
                  }
                  if ((0x7ffe08800000000L & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  else if ((0x1000001000000000L & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAdd(17); }
                  }
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 31:
                  if ((0x57ffe89800000000L & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAdd(17); }
                  }
                  if ((0x7ffe08800000000L & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  else if ((0x1000001000000000L & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAdd(17); }
                  }
                  break;
               case 0:
                  if ((0x7ffe08800000000L & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  else if ((0x1000001000000000L & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAdd(17); }
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 4)
                        kind = 4;
                  }
                  else if (curChar == 42)
                     { jjAddStates(7, 8); }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 123)
                        kind = 123;
                     { jjCheckNAddStates(0, 3); }
                  }
                  else if ((0x2800000000L & l) != 0L)
                     { jjCheckNAddStates(4, 6); }
                  else if (curChar == 46)
                     { jjCheckNAdd(10); }
                  else if (curChar == 45)
                     { jjCheckNAddTwoStates(9, 14); }
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjCheckNAddStates(4, 6); }
                  break;
               case 2:
                  if ((0x2400L & l) != 0L && kind > 3)
                     kind = 3;
                  break;
               case 3:
                  if (curChar == 10 && kind > 3)
                     kind = 3;
                  break;
               case 4:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if ((0x2400L & l) != 0L && kind > 4)
                     kind = 4;
                  break;
               case 6:
                  if (curChar == 10 && kind > 4)
                     kind = 4;
                  break;
               case 7:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 45)
                     { jjCheckNAddTwoStates(9, 14); }
                  break;
               case 9:
                  if (curChar == 46)
                     { jjCheckNAdd(10); }
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 12:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(13); }
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  { jjCheckNAdd(13); }
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  { jjCheckNAddStates(0, 3); }
                  break;
               case 15:
                  if ((0x7ffe08800000000L & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  break;
               case 16:
                  if ((0x1000001000000000L & l) == 0L)
                     break;
                  if (kind > 124)
                     kind = 124;
                  { jjCheckNAdd(17); }
                  break;
               case 17:
                  if ((0x57ffe89800000000L & l) == 0L)
                     break;
                  if (kind > 124)
                     kind = 124;
                  { jjCheckNAdd(17); }
                  break;
               case 18:
                  if (curChar == 42)
                     { jjAddStates(7, 8); }
                  break;
               case 19:
                  if (curChar == 42 && kind > 135)
                     kind = 135;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 33:
                  if ((0x7fffffe87ffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAdd(17); }
                  }
                  break;
               case 32:
                  { jjCheckNAddStates(4, 6); }
                  if ((0x7fffffe87ffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAdd(17); }
                  }
                  break;
               case 23:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 29;
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 31:
                  if ((0x7fffffe87ffffffL & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAdd(17); }
                  }
                  if ((0x7fffffe87ffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAdd(17); }
                  }
                  break;
               case 0:
                  if ((0x7fffffe87ffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 124)
                        kind = 124;
                     { jjCheckNAdd(17); }
                  }
                  break;
               case 1:
                  { jjCheckNAddStates(4, 6); }
                  break;
               case 11:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(9, 10); }
                  break;
               case 15:
                  if ((0x7fffffe87ffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(15, 16); }
                  break;
               case 16:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 124)
                     kind = 124;
                  { jjCheckNAdd(17); }
                  break;
               case 17:
                  if ((0x7fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 124)
                     kind = 124;
                  { jjCheckNAdd(17); }
                  break;
               case 20:
                  if (curChar == 108)
                     { jjCheckNAdd(19); }
                  break;
               case 21:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 24:
                  if (curChar == 114)
                     { jjCheckNAdd(19); }
                  break;
               case 25:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 32:
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(4, 6); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 31 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\151\156\163\164\141\156\143\145", 
"\155\141\170\55\151\156\163\164\141\156\143\145\77", "\155\151\156\55\151\156\163\164\141\156\143\145\77", 
"\141\154\154\55\151\156\163\164\141\156\143\145\163\77", "\155\141\170\55\162\145\154\141\164\145\144\77", 
"\155\151\156\55\162\145\154\141\164\145\144\77", "\155\141\170\55\163\165\142\163\77", 
"\155\141\170\55\147\55\163\165\142\163\77", "\155\141\170\55\154\55\163\165\142\163\77", 
"\155\141\170\55\153\144\55\163\165\142\163\77", "\155\151\156\55\163\165\142\163\77", 
"\155\151\156\55\147\55\163\165\142\163\77", "\155\151\156\55\154\55\163\165\142\163\77", 
"\155\151\156\55\153\144\55\163\165\142\163\77", "\155\141\170\55\163\141\164\77", "\155\151\156\55\163\141\164\77", 
"\143\154\141\163\163\151\146\171\77", "\155\141\170\55\166\141\162\77", "\155\151\156\55\166\141\162\77", 
"\163\141\164\77", "\144\145\146\165\172\172\151\146\171\55\154\157\155\77", 
"\144\145\146\165\172\172\151\146\171\55\163\157\155\77", "\144\145\146\165\172\172\151\146\171\55\155\157\155\77", "\142\156\160\77", 
"\144\145\146\151\156\145\55\164\162\165\164\150\55\143\157\156\163\164\141\156\164", "\144\145\146\151\156\145\55\143\157\156\143\145\160\164", 
"\144\145\146\151\156\145\55\160\162\151\155\151\164\151\166\145\55\143\157\156\143\145\160\164", "\145\161\165\151\166\141\154\145\156\164\55\143\157\156\143\145\160\164\163", 
"\144\145\146\151\156\145\55\146\165\172\172\171\55\143\157\156\143\145\160\164", "\144\145\146\151\156\145\55\146\165\172\172\171\55\156\165\155\142\145\162", 
"\144\145\146\151\156\145\55\146\165\172\172\171\55\156\165\155\142\145\162\55\162\141\156\147\145", 
"\144\145\146\151\156\145\55\146\165\172\172\171\55\163\151\155\151\154\141\162\151\164\171", 
"\144\145\146\151\156\145\55\146\165\172\172\171\55\145\161\165\151\166\141\154\145\156\143\145", "\162\145\154\141\164\145\144", 
"\144\145\146\151\156\145\55\155\157\144\151\146\151\145\162", "\146\165\156\143\164\151\157\156\141\154", 
"\164\162\141\156\163\151\164\151\166\145", "\162\145\146\154\145\170\151\166\145", 
"\163\171\155\155\145\164\162\151\143", "\151\155\160\154\151\145\163\55\162\157\154\145", 
"\151\156\166\145\162\163\145", "\151\156\166\145\162\163\145\55\146\165\156\143\164\151\157\156\141\154", 
"\144\151\163\152\157\151\156\164", "\144\151\163\152\157\151\156\164\55\165\156\151\157\156", 
"\162\141\156\147\145", "\144\157\155\141\151\156", "\143\157\156\163\164\162\141\151\156\164\163", 
"\144\145\146\151\156\145\55\146\165\172\172\171\55\154\157\147\151\143", "\143\162\151\163\160\55\143\157\156\143\145\160\164", 
"\143\162\151\163\160\55\162\157\154\145", "\42", "\141\156\144", "\147\55\141\156\144", "\154\55\141\156\144", 
"\151\155\160\154\151\145\163", "\147\55\151\155\160\154\151\145\163", 
"\153\144\55\151\155\160\154\151\145\163", "\154\55\151\155\160\154\151\145\163", "\172\55\151\155\160\154\151\145\163", 
"\157\162", "\147\55\157\162", "\154\55\157\162", "\156\157\164", "\163\157\155\145", 
"\142\55\163\157\155\145", "\141\154\154", "\52\164\157\160\52", "\52\142\157\164\164\157\155\52", 
"\167\55\163\165\155", "\167\55\163\165\155\55\172\145\162\157", "\167\55\155\141\170", 
"\167\55\155\151\156", "\163\145\154\146", "\165\141", "\154\141", "\157\167\141", 
"\161\55\157\167\141", "\143\150\157\161\165\145\164", "\163\165\147\145\156\157", 
"\161\55\163\165\147\145\156\157", "\164\165\141", "\164\154\141", "\154\165\141", "\154\154\141", "\146\53", 
"\146\55", "\146\52", "\146\57", "\163\151\147\155\141\55\143\157\165\156\164", 
"\143\162\151\163\160", "\154\145\146\164\55\163\150\157\165\154\144\145\162", 
"\162\151\147\150\164\55\163\150\157\165\154\144\145\162", "\164\162\151\141\156\147\165\154\141\162", 
"\164\162\141\160\145\172\157\151\144\141\154", "\154\151\156\145\141\162", "\155\157\144\151\146\151\145\144", 
"\154\151\156\145\141\162\55\155\157\144\151\146\151\145\162", "\164\162\151\141\156\147\165\154\141\162\55\155\157\144\151\146\151\145\162", 
"\163\150\157\167\55\166\141\162\151\141\142\154\145\163", 
"\163\150\157\167\55\141\142\163\164\162\141\143\164\55\146\151\154\154\145\162\163", 
"\163\150\157\167\55\141\142\163\164\162\141\143\164\55\146\151\154\154\145\162\163\55\146\157\162", 
"\163\150\157\167\55\143\157\156\143\162\145\164\145\55\146\151\154\154\145\162\163", 
"\163\150\157\167\55\143\157\156\143\162\145\164\145\55\146\151\154\154\145\162\163\55\146\157\162", 
"\163\150\157\167\55\143\157\156\143\162\145\164\145\55\151\156\163\164\141\156\143\145\55\146\157\162", "\163\150\157\167\55\151\156\163\164\141\156\143\145\163", 
"\163\150\157\167\55\143\157\156\143\145\160\164\163", "\163\150\157\167\55\154\141\156\147\165\141\147\145", "\146\162\145\145", 
"\142\151\156\141\162\171", "\154\165\153\141\163\151\145\167\151\143\172", "\172\141\144\145\150", 
"\143\154\141\163\163\151\143\141\154", "\53", "\55", "\52", "\74\75", "\76\75", "\75", null, null, "\50", "\51", 
"\133", "\135", "\173", "\175", "\43", "\54", "\52\163\164\162\151\156\147\52", 
"\52\142\157\157\154\145\141\156\52", null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   9, 10, 11, 14, 1, 2, 4, 23, 30, 12, 13, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000200L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public ParserTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public ParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 31; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xfffffffffffffff1L, 0xffffffffffffffffL, 0xffL, 
};
static final long[] jjtoSkip = {
   0xeL, 0x0L, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x8L, 0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[31];
    private final int[] jjstateSet = new int[2 * 31];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
